SPOOL 03-proc1_api.lst


PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Creation des APIs de tables   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;

PROMPT Creating Table API Error Package CG$ERRORS
@@02-API\CSCI_CPT\cdsaper.PKS
@@02-API\CSCI_CPT\cdsaper.PKB

PROMPT Creating Table API Package Specification
@@02-API\CSCI_CPT\SPC.PKS
@@02-API\CSCI_CPT\CAP.PKS
@@02-API\CSCI_CPT\CPTT.PKS
@@02-API\CSCI_CPT\FCT.PKS
@@02-API\CSCI_CPT\DC.PKS
@@02-API\CSCI_CPT\JSP.PKS
@@02-API\CSCI_CPT\FC.PKS
@@02-API\CSCI_CPT\DCON.PKS
@@02-API\CSCI_CPT\RIC.PKS
@@02-API\CSCI_CPT\CPT.PKS

PROMPT
PROMPT Creating Table API Package Body 
@@02-API\CSCI_CPT\SPC.PKB
@@02-API\CSCI_CPT\CAP.PKB
@@02-API\CSCI_CPT\CPTT.PKB
@@02-API\CSCI_CPT\FCT.PKB
@@02-API\CSCI_CPT\DC.PKB
@@02-API\CSCI_CPT\JSP.PKB
@@02-API\CSCI_CPT\FC.PKB
@@02-API\CSCI_CPT\DCON.PKB
@@02-API\CSCI_CPT\RIC.PKB
@@02-API\CSCI_CPT\CPT.PKB

PROMPT
PROMPT Creating Triggers
@@02-API\CSCI_CPT\SPC.TRG
@@02-API\CSCI_CPT\CAP.TRG
@@02-API\CSCI_CPT\CPTT.TRG
@@02-API\CSCI_CPT\FCT.TRG
@@02-API\CSCI_CPT\DC.TRG
@@02-API\CSCI_CPT\JSP.TRG
@@02-API\CSCI_CPT\FC.TRG
@@02-API\CSCI_CPT\DCON.TRG
@@02-API\CSCI_CPT\RIC.TRG
@@02-API\CSCI_CPT\CPT.TRG

PROMPT
PROMPT Finished.



SPOOL OFF

COMMIT;