create or replace PROCEDURE Purge_table_temp AS

BEGIN

    DELETE FROM RIC_TEMP;
    DELETE FROM RIC02_TEMP;
    
    DELETE FROM STAT01_NBPOS_CAP;
    DELETE FROM STAT01_NBPOS_CPT;
    DELETE FROM STAT01_NBPOS_CPTT;
    DELETE FROM STAT01_NBPOS_FC;
 
END;
/
