--
-- Script de suppression des tables du CSCI-ADM
-- Anass RACH - 10/10/2013
--

DROP TABLE "CANDIDAT" CASCADE CONSTRAINTS;
DROP TABLE "ENSEIGNANT" CASCADE CONSTRAINTS;
DROP TABLE "ETUDIANT" CASCADE CONSTRAINTS;
DROP TABLE "PROMOTION" CASCADE CONSTRAINTS;
