 --
 -- Script de suppression des domaines dynamiques
 -- Anass RACH - 10-10-2013
 --
 
 
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'TYPE_EMPLOI';
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'MOYEN_OBTENTION_EMPLOI';
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'PROCESSUS_STAGE';
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'SERVICE';
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'DOMAINE_ACTIVITE';
DELETE FROM CG_REF_CODES WHERE RV_DOMAIN = 'FONCTION';