-- INSERTING into COMPETENCE_TRANSVERSALE
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ORG','CTS','Organisation',1,'Capacité à prévoir, fixer les règles à suivre, établir les plans d''action correspondants et allouer les ressources nécessaires.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'COO','CTS','Coopération',2,'Capacité de travailler au sein d''une équipe, à s''adapter à des interlocuteurs divers et variés et à contribuer activement à l''avancée d''objectifs communs.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'COM','CTS','Communication',3,'Capacité à communiquer oralement et à produire avec efficacité des documents suffisamment clairs pour être compréhensibles par le client et tous les membres de l''équipe.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'TRP','CTS','Transfert/Partage',4,'Capacité à diffuser un savoir, une compétence, une information à ses collègues dans un but d''appropriation ou de meilleure compréhension par ceux-ci.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ANA','CTS','Analyse',5,'Capacité d''absorber, de comparer, de corréler et de synthétiser des informations et des données, d''en extraire l''essentiel pour réagir avec rapidité.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ABS','CTS','Abstraction',6,'Capacité à abstraire, à conceptualiser et à  modéliser de manière simple et efficace.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ING','CTS','Ingéniosité',7,'Capacité à faire preuve d''inventivité et de créativité en cohérence avec les exigences et les contraintes technologiques ou autres.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'INN','CTS','Innovation',8,'Capacité de curiosité, de perspicacité et d''esprit d''initiative afin de faciliter l''émergence de nouvelles solutions toujours plus efficaces et plus productives.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ECF','CTS','Ecoute/Flexibilité',9,'Capacité à écouter et comprendre, envisager d''autres points de vue que le sien.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'ADA','CTS','Adaptabilité',10,'Capacité à s''adapter à de nouveaux environnements organisationnels et techniques et à enrichir ses connaissances de manière continue.');
Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'REF','CTS','Réflexivité',11,'Capacité à observer ses propres pratiques, à les évaluer et à les modifier à des fins d''amélioration.');
--Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',1,null,'TEST','CTS','Test competence pour une famille',12,'Compétence test');

--competence personnelle
--Insert into "COMPETENCE_TRANSVERSALE" ("CODE_MCP","ID_FCT","ID_SPC","CODE_COMPETENCE","STD_PERSO","DESIGNATION","ORDRE","DESCRIPTION") values ('MOD01',null,null,'NEW','CTP','Competence perso',13,'Distributeur de bonbons...');
