-- INSERTING into POSITIONNEMENT

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,1,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,2,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,3,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,1,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,4,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,5,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,6,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,7,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,8,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,2,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,9,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,10,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,11,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,12,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,13,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,3,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,14,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,16,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,17,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,19,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,21,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,5,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,22,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,23,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,24,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,25,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,28,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,29,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,7,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,30,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,31,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,32,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,33,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,8,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,34,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,35,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,36,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,37,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,9,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,38,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,40,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,41,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,10,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,42,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,43,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,44,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,11,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,45,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,12,null,null,'MAT',1);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,46,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,47,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,48,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (1,null,13,null,null,'MAT',1);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,1,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,2,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,3,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,4,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,5,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,7,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,8,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,9,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,10,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (1,null,null,null,11,'CPT',2);

-----------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,1,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,2,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,3,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,1,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,4,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,5,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,6,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,7,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,8,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,2,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,9,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,10,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,11,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,12,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,3,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,14,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,16,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,17,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,19,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,21,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,5,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,22,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,23,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,24,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,25,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,27,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,28,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,29,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,7,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,30,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,31,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,32,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,33,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,8,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,34,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,35,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,36,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,37,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,9,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,38,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,39,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,40,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,41,null,null,null,'MAT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,10,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,42,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,43,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,44,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,11,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,45,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,12,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,46,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,47,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,48,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (2,null,13,null,null,'MAT',2);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,1,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,2,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,3,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,4,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,7,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,8,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,9,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,10,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (2,null,null,null,11,'CPT',3);

-----------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,1,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,2,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,3,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,1,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,4,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,5,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,6,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,7,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,8,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,2,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,9,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,10,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,11,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,12,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,3,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,14,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,16,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,17,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,19,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,21,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,5,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,22,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,23,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,24,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,25,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,27,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,28,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,29,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,7,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,30,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,31,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,32,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,33,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,8,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,34,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,35,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,36,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,37,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,9,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,38,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,39,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,40,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,41,null,null,null,'MAT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,10,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,42,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,43,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,44,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,11,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,45,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,12,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,46,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,47,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,48,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (3,null,13,null,null,'MAT',2);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,1,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,2,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,3,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,4,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,7,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,8,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,9,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,10,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (3,null,null,null,11,'CPT',3);

--------------------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,1,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,2,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,3,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,1,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,4,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,5,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,6,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,7,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,8,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,2,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,9,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,10,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,11,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,12,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,13,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,3,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,14,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,16,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,17,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,19,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,21,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,5,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,22,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,23,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,24,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,25,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,28,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,29,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,7,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,30,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,31,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,32,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,33,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,8,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,34,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,35,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,36,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,37,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,9,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,38,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,40,null,null,null,'MAT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,41,null,null,null,'MAT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,10,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,42,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,43,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,44,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,11,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,45,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,12,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,46,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,47,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,48,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (4,null,13,null,null,'MAT',4);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,1,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,2,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,3,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,4,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,5,'CPT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,7,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,8,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,9,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,10,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (4,null,null,null,11,'CPT',3);

---------------------------------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,1,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,2,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,3,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,1,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,4,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,5,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,6,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,7,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,8,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,2,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,9,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,10,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,11,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,12,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,3,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,14,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,16,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,17,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,4,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,18,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,19,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,21,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,5,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,22,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,23,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,24,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,25,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,28,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,29,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,7,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,30,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,31,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,32,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,33,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,8,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,34,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,35,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,36,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,37,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,9,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,38,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,40,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,41,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,10,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,42,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,43,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,44,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,11,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,45,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,12,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,46,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,47,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,48,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (5,null,13,null,null,'MAT',1);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,1,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,2,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,3,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,4,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,7,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,8,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,9,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,10,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (5,null,null,null,11,'CPT',2);

---------------------------------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,1,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,2,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,3,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,1,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,4,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,5,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,6,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,7,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,8,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,2,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,9,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,10,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,11,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,12,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,3,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,14,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,15,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,16,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,17,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,19,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,20,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,21,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,5,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,22,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,23,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,24,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,25,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,28,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,29,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,7,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,30,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,31,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,32,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,33,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,8,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,34,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,35,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,36,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,37,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,9,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,38,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,40,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,41,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,10,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,42,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,43,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,44,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,11,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,45,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,12,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,46,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,47,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,48,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (6,null,13,null,null,'MAT',4);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,1,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,2,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,3,'CPT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,4,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,7,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,8,'CPT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,9,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,10,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (6,null,null,null,11,'CPT',4);

-- Promotion 2004 2005 -----------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,1,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,2,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,3,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,1,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,4,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,5,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,6,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,7,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,8,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,2,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,9,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,10,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,11,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,12,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,3,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,14,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,15,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,16,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,17,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,4,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,18,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,19,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,20,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,21,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,5,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,22,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,23,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,24,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,25,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,28,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,29,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,7,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,30,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,31,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,32,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,33,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,8,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,34,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,35,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,36,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,37,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,9,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,38,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,40,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,41,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,10,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,42,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,43,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,44,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,11,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,45,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,12,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,46,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,47,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,48,null,null,null,'MAT',1);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (7,null,13,null,null,'MAT',1);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,1,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,2,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,3,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,4,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,7,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,8,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,9,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,10,'CPT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (7,null,null,null,11,'CPT',2);

---------------------------------------------------------------------------

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,1,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,2,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,3,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,1,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,4,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,5,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,6,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,7,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,8,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,2,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,9,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,10,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,11,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,12,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,13,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,3,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,14,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,15,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,16,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,17,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,4,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,18,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,19,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,20,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,21,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,5,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,22,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,23,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,24,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,25,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,26,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,6,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,27,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,28,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,29,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,7,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,30,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,31,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,32,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,33,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,8,null,null,'MAT',2);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,34,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,35,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,36,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,37,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,9,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,38,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,39,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,40,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,41,null,null,null,'MAT',2);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,10,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,42,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,43,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,44,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,11,null,null,'MAT',4);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,45,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,12,null,null,'MAT',3);

Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,46,null,null,null,'MAT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,47,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,48,null,null,null,'MAT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_MATURITE") values (8,null,13,null,null,'MAT',4);


Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,1,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,2,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,3,'CPT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,4,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,5,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,6,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,7,'CPT',4);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,8,'CPT',5);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,9,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,10,'CPT',3);
Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,null,11,'CPT',4);


------- test Competence--------------------------
--Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,1,null,'CPT',1);
--Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,2,null,'CPT',2);
--Insert into "POSITIONNEMENT" ("ID_SPC","ID_CAP","ID_FC","ID_CPT","ID_CPTT","TYPE_POSITIONNEMENT","NIVEAU_COMPETENCE") values (8,null,null,3,null,'CPT',3);
















