-- INSERTING into RECUEIL_INDIVIDUEL_COMPETENCE
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (1,'ILI4-001','ric01',to_date('2005-10-07','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (2,'ILI4-001','ric01',to_date('2005-10-11','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (3,'ILI4-001','ric01',to_date('2005-10-08','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (4,'ILI4-001','ric01',to_date('2005-10-03','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (5,'ILI4-001','ric01',to_date('2005-10-03','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (6,'ILI4-001','ric01',to_date('2005-10-12','yyyy-mm-dd'),'IT1',null,null);

Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (1,'ILI4-002','ric02',to_date('2006-02-14','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (2,'ILI4-002','ric02',to_date('2006-02-09','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (3,'ILI4-002','ric02',to_date('2006-02-11','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (4,'ILI4-002','ric02',to_date('2006-02-10','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (5,'ILI4-002','ric02',to_date('2006-02-11','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (6,'ILI4-002','ric02',to_date('2006-02-08','yyyy-mm-dd'),'IT2',null,null);

Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (7,'ILI3-001','ric01',to_date('2004-10-10','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (8,'ILI3-001','ric01',to_date('2004-10-12','yyyy-mm-dd'),'IT1',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (7,'ILI3-002','ric02',to_date('2005-02-11','yyyy-mm-dd'),'IT2',null,null);
Insert into "RECUEIL_INDIVIDUEL_COMPETENCE" ("ID_SPC","NO_DEMANDE_RIC","NUMERO_RIC","DATE_PHOTOGRAPHIE","TYPE_RIC","LIBELLE_RIC","AUTRE_COMPETENCE") values (8,'ILI3-002','ric02',to_date('2005-02-08','yyyy-mm-dd'),'IT2',null,null);
