-- INSERTING into SUIVI_PERSONNEL_COMPETENCE

Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','1492057895k',to_date('2005-10-07','yyyy-mm-dd'),'mon premier SPC',null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','06816q06pf3',to_date('2005-10-11','yyyy-mm-dd'),null,null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','1499110659h',to_date('2005-10-08','yyyy-mm-dd'),null,null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','1893029650z',to_date('2005-10-03','yyyy-mm-dd'),null,null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','1493003704n',to_date('2005-10-03','yyyy-mm-dd'),null,null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','1493010305n',to_date('2005-10-12','yyyy-mm-dd'),null,null);

Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','20103526',to_date('2004-10-06','yyyy-mm-dd'),null,null);
Insert into "SUIVI_PERSONNEL_COMPETENCE" ("CODE_MCP","NO_ETUDIANT_NAT","DATE_DEBUT","COMMENTAIRE","DATE_FIN") values ('MOD01','18986523',to_date('2004-10-11','yyyy-mm-dd'),null,null);


--UPDATE COMPETENCE_TRANSVERSALE SET ID_SPC=1 WHERE ID_CPTT=13;