create or replace TRIGGER AIR_COMPETENCE AFTER INSERT ON COMPETENCE 
FOR EACH ROW 
DECLARE
    CURSOR curs_spc IS
 SELECT spc.ID_SPC FROM SUIVI_PERSONNEL_COMPETENCE spc, FAMILLE_COMPETENCE fc, DOMAINE_COMPETENCE dc
 WHERE spc.CODE_MCP = dc.CODE_MCP
 AND dc.ID_DC = fc.ID_DC
 AND fc.ID_FC = :NEW.ID_FC;

BEGIN

   for p in curs_spc
     loop
       INSERT INTO POSITIONNEMENT (ID_SPC, ID_CPT, ID_FC_CAP, TYPE_POSITIONNEMENT) VALUES (p.ID_SPC, :NEW.ID_CPT, :NEW.ID_FC, 'CPT');
     end loop;

END;
/
