create or replace TRIGGER AIR_COMPETENCE_TRANSVERSALE AFTER INSERT ON COMPETENCE_TRANSVERSALE
FOR EACH ROW

DECLARE
    CURSOR curs_spc IS
    SELECT ID_SPC FROM SUIVI_PERSONNEL_COMPETENCE WHERE CODE_MCP = :NEW.CODE_MCP;

BEGIN

  IF :NEW.STD_PERSO='CTS' THEN
     for p in curs_spc
     loop
       INSERT INTO POSITIONNEMENT (ID_SPC, ID_CPTT, TYPE_POSITIONNEMENT) VALUES (p.ID_SPC, :NEW.ID_CPTT, 'CPT');
     end loop;

  ELSIF :NEW.STD_PERSO='CTP' THEN
 INSERT INTO POSITIONNEMENT (ID_SPC, ID_CPTT, TYPE_POSITIONNEMENT) VALUES (:NEW.ID_SPC, :NEW.ID_CPTT, 'CPT');

  END IF;

END;
/
