--
-- Script de création des index du CSCI-ADM
-- Moctar SALEH NJOYA  11 octobre 2013

PROMPT Creating Index 'ETU_PRO_FK_I'
CREATE INDEX ETU_PRO_FK_I ON ETUDIANT
 (ANNEE_PRO)
/

PROMPT Creating Index 'CAN_PRO_FK_I'
CREATE INDEX CAN_PRO_FK_I ON CANDIDAT
 (ANNEE_PRO)
/

PROMPT Creating Index 'EMP_ENT_FK_I'
CREATE INDEX EMP_ENT_FK_I ON EMPLOYE
 (NO_ENTREPRISE)
/

PROMPT Creating Index 'POE_ENT_FK_I'
CREATE INDEX POE_ENT_FK_I ON POSTE_ENTREPRISE
 (NO_ENTREPRISE)
/

PROMPT Creating Index 'POE_DIP_FK_I'
CREATE INDEX POE_DIP_FK_I ON POSTE_ENTREPRISE
 (NO_ETUDIANT_NAT)
/

PROMPT Creating Index 'DIP_ETU_FK_I'
CREATE INDEX DIP_ETU_FK_I ON DIPLOME
 (NO_ETUDIANT_NAT)
/

PROMPT Creating Index 'EMP_DIP_FK_I'
CREATE INDEX EMP_DIP_FK_I ON EMPLOYE
 (NO_ETUDIANT_NAT)
/

PROMPT Creating Index 'EMP_DIP_FK_I'
CREATE INDEX EMP_DIP_FK_I ON EMPLOYE
 (NO_ETUDIANT_NAT)
/

