SPOOL 05-jeu_essai.lst

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~ SIGILI_R2 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@@SIGILI_R2\CG_REF_CODES.sql
@@SIGILI_R2\PROMOTION.sql
@@SIGILI_R2\COMPAGNIE.sql
@@SIGILI_R2\ETUDIANT.sql
@@SIGILI_R2\AUTHENTIFICATION.sql


PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~ CSCI_CPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@@CSCI_CPT\MODELE_COMPETENCE.sql
@@CSCI_CPT\DOMAINE_COMPETENCE.sql
@@CSCI_CPT\FAMILLE_COMPETENCE.sql
@@CSCI_CPT\CAPACITE.sql
@@CSCI_CPT\DOMAINE_CONNAISSANCE.sql
@@CSCI_CPT\COMPETENCE.sql
@@CSCI_CPT\FAMILLE_COMPETENCE_TRANSVERSAL.sql
@@CSCI_CPT\COMPETENCE_TRANSVERSALE.sql
@@CSCI_CPT\CT_FC.sql
@@CSCI_CPT\SUIVI_PERSONNEL_COMPETENCE.sql
@@CSCI_CPT\POSITIONNEMENT.sql
@@CSCI_CPT\JOURNAL_SUIVI_PERSONNEL.sql
@@CSCI_CPT\DEMANDE_RIC.sql
@@CSCI_CPT\RECUEIL_INDIVIDUEL_COMPETENCE.sql
@@CSCI_CPT\RIC_POSITIONNEMENT.sql


PROMPT~~~~~~~~~~~~~~~~~~~ Modifications des sequences ~~~~~~~~~~~~~~~~~~~~~~

@@Sequences.sql


SPOOL OFF
COMMIT;




