-- INSERTING into ETUDIANT

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-01','2006-2007','CILI5.1','20002378','H','Bellion','Alexis',to_date('22/03/80','DD/MM/RR'),'Pau','CEL','Française','06 62 83 31 75','02 98 02 11 96','alexis.bellion@gmail.com','54 rue de la République','29200','BREST','FRANCE','54 rue de la République','29200','BREST','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'ABE', 'bellioal');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-02','2006-2007','CILI5.2','20303427','H','Bodéré','Erwan',to_date('26/12/82','DD/MM/RR'),'Quimper','CEL','Française',null,'02 98 58 51 89','erwan146@caramail.com','573 route de Pors Carn','29760','PENMARC''H','FRANCE','573 route de Pors Carn','29760','PENMARC''H','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'EB', 'bodereer');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-03','2006-2007','CILI5.2','20102148','H','Clément','Pierre-Yves',to_date('11/09/83','DD/MM/RR'),'Brest','CEL','Française',null,'02 98 07 70 28','p_clement@hotmail.com','10 rue des Cormorans','29850','GOUESNOU','France','10 rue des Cormorans','29850','GOUESNOU','France','Master 1 - Informatique Logiciel','Université de Bretagne Occidentale', 'PYC', 'clemenpi');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-04','2006-2007','CILI5.2','20403661','L','Genoud','Aude',to_date('16/02/83','DD/MM/RR'),'Chambray','CEL','Française','06 61 44 06 68',null,'genoud_aude@yahoo.fr','Jardin des Sciences 10 rue Cuirasse Bretagne','29200','BREST','FRANCE','Jardin des Sciences 10 rue Cuirasse Bretagne','29200','BREST','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'AG','genoudau');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-05','2006-2007','CILI5.1','20403718','H','Guénard','Adrien',to_date('23/01/83','DD/MM/RR'),'Poitiers','CEL','Française','06 07 15 61 17',null,'adrien.guenard@laposte.net','2 rue de la Piscine','79450','St Aubin Le Cloud','FRANCE','2 rue de la Piscine','79450','St Aubin Le Cloud','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'AGU', 'guenarad');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-07','2006-2007','CILI5.1','20303396','H','Lucas','Rodolphe',to_date('06/03/81','DD/MM/RR'),'Châteauroux','CEL','Française','06 83 00 62 47',null,'rodolphe.lucas@gmail.com','4 Ter avenue Victor Le Gorgeu','29200','BREST','FRANCE','4 Ter avenue Victor Le Gorgeu','29200','BREST','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'RLU','lucasrod');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-08','2006-2007','CILI5.2','20403679','H','Le Trocquer','Mickaël',to_date('05/12/83','DD/MM/RR'),'Pabu','CEL','Française','06 23 12 14 83',null,'letrocquermickael-iup@yahoo.fr','19 rue de Justice','22140','Bégard','FRANCE','19 rue de Justice','22140','Bégard','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'MLT','le_tromi');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-06','2006-2007','CILI5.2','20201143','H','Moras','Maxime',to_date('21/04/83','DD/MM/RR'),'Landivisiau','CEL','Française','06 88 93 81 04',null,'maxime.moras@libertysurf.fr','3 bis place de la gare','29630','Plougasnou','FRANCE','3 bis place de la gare','29630','Plougasnou','FRANCE','Master 1 - Informatique Logiciel','Université de Bretagne Occidentale', 'MM', 'morasmax');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-09','2006-2007','CILI5.2','20200852','L','Pochard','Laëticia',to_date('09/07/84','DD/MM/RR'),'Brest','CEL','Française','06 65 26 42 94','02 98 84 61 01','laetitia0907@msn.com','Keraudry','29490','Guipavas','FRANCE','Keraudry','29490','Guipavas','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'LP','pocharla');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-10','2006-2007','CILI5.1','20200802','L','Rosec','Fabienne',to_date('09/09/84','DD/MM/RR'),'Brest','CEL','Française','06 76 08 79 09',null,'fabienne.rosec@wanadoo.fr','14 Streat ar Vran','29430','Plounevez-Lochrist','FRANCE','14 Streat ar Vran','29430','Plounevez-Lochrist','FRANCE','Master 1 - Informatique Logiciel','Université de Bretagne Occidentale', 'FRO', 'rosecfab');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-11','2006-2007','CILI5.1','20404425','L','Sibeth','Nolwenn',to_date('04/01/82','DD/MM/RR'),'Redon','CEL','Française','06 70 19 14 70','02 98 49 63 15','nolwenn.sibeth@orange.fr','3 petite rue Vauban Résidence Recouvrance','29200','BREST','FRANCE','Cavardin','44460','St Nicolas de Redon','FRANCE','Master 1 - Informatique Logiciel','Université de Bretagne Occidentale', 'NSI', 'sibethno');

Insert into "ETUDIANT" ("NO_ETUDIANT_NAT","ANNEE_PRO","CODE_COM","NO_ETUDIANT_UBO","SEXE","NOM","PRENOM","DATE_NAISSANCE","LIEU_NAISSANCE","SITUATION","NATIONALITE","TEL_PORT","TEL_FIXE","EMAIL","ACTU_ADRESSE","ACTU_CP","ACTU_VILLE","ACTU_PAYS","PERM_ADRESSE","PERM_CP","PERM_VILLE","PERM_PAYS","DERNIER_DIPLOME","UNIVERSITE","SIGLE_ETU","COMPTE_CRI") 
values ('CILI5-12','2006-2007','CILI5.1','20200685','H','Urien','Nicolas',to_date('27/01/83','DD/MM/RR'),'Morlaix','CEL','Française','06 22 75 82 49',null,'nicolasurien@vieillescharrues.asso.fr','9 rue Louis Guilloux','29600','St Martin des Champs','FRANCE','9 rue Louis Guilloux','29600','St Martin des Champs','FRANCE','Master 1 - IUP Ingénierie Informatique','Université de Bretagne Occidentale', 'NUR', 'uriennic');
